name: jkorb
favicon: null
layout_spectrum: 0.42740570893511176
typography_spectrum: 0.12190270377323031
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.6429408602416515
  lightness: 0.2770094536244869
  saturation: 0.947479990310967
  rhythmicContrast: 0.3655305386055261
purpose: []
